# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4b206c0b8d3d47d28cbdab3bdd93a9a60702347985246c9d963f5cdb5eb77ea5e9f0aa6ceb7e114502289a0182ed60caeda1c0585047e74aae3091d0c9f7c21

test:
  secret_key_base: 5b722380e0465fc49182a1fed768376f81475b2aa4a5cfda5ecfd252459a40ef02a5c008e34f2e607238a1016d4dc071cb2a4fa5a2bdc6c76cf1143a3818a413

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
